### ISSUE TITLE
Update dependencies and do a release

### ISSUE THREAD

**Issue by Follpvosten** [jaemk/migrant_lib#31]
Hi! I just noticed that migrant_lib still depends on tokio-postgres 0.5, so it's pulling in tokio 0.2 into our project which is built on tokio 1.0. I think I'm also having some tokio runtime issues because of that.
Would it be possible to update the dependencies and release a new version?
Or alternatively, would a PR updating the deps be welcome in case it's too much work?

**Comment by jaemk** [comment]
A PR would be welcome! I can update and release a new version this weekend otherwise

**Comment by Follpvosten** [comment]
Just opened #32

**Comment by jaemk** [comment]
released in `0.31.0`
